exports.quotes = [
  "What is coming is better than what has gone.",
  "Every day, we have two choices. Evolve or repeat.",
  "Though it may seem difficult, remember that your life is as good as your mindset.",
  "You are abundant. There is always enough.",
  "It's not things that upset us, but our judgements about things.",
  "There is no good or bad without us. There is only perception. There is the event itself, and the story we tell ourselves about what it means.",
  "Treat each and every moment - no matter how challenging - as something to be embraced. And if it is challenging, accept it and be better for it. So that like oxygen to a fire, obstacles and adversity become fuel for your potential.",
  "Celebrate not only who you've become, but who you could've become and fought not to.",
  "When things change inside you, things change around you.",
  "You can live today with passion and purpose.",
  "Today, be gentle with yourself.",
  "Today, accept and let go of the things you can't control. Focus your energy on the things that you can.",
  "Mental health isn't a battle to be won. It is a journey to continue walking.",
  "Take a moment to look around and appreciate the things that are going right as well.",
  "As your thoughts continuously ramble on, remember, you are the observer of your thoughts. They will continue to flow and tangle and persist. But you choose what you internalize from them; you choose what you hear vs. what you actually listen to.",
  "Growth is uncomfortable, because you've never been here before. Welcome.",
  "Your direction is more important than your speed.",
  "You're not always going to be motivated, so you must be disciplined.",
];
